# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55fec5bce750f30b2ed499eadc4d2ace4ab283e33e3cb396c855a8a00592df7a8d02159cb79d6da1f4833af350e66cdefe8556884063d942e4bdca2ae59635cb

test:
  secret_key_base: bd2c842af0fb9527ba854aa3dd5d085e997f919b2f91492251091150f43344cc9780da25b548ca096a98e5ebed37c53ae96e096ba227062d22356b9d590551f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
